//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resourceproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookedlist
    {
        public int Id { get; set; }
        public System.DateTime Startdate { get; set; }
        public System.DateTime Enddate { get; set; }
        public string Email { get; set; }
        public int Resource_Id { get; set; }
    }
}
