//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resourceproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duration
    {
        public System.DateTime Startdate { get; set; }
        public System.DateTime Enddate { get; set; }
        public int ResourceId { get; set; }
        public int UserId { get; set; }
    }
}
